# docker-compose.yml
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    #ports:
    #  - "5230:5230"
    networks:
      - nginx-net
    volumes:
      - ./data:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=5230

networks:
  nginx-net:
    external: true
